# Generated by Django 5.2.6 on 2025-09-05 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configapp', '0002_todolist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='done_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
