# Generated by Django 5.2.6 on 2025-09-08 08:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configapp', '0004_user_phonenumber_user_sms_kod_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phonenumber',
            field=models.CharField(max_length=13, unique=True, validators=[django.core.validators.RegexValidator(message='Telefon raqam +998 bilan boshlanishi va jami 13 ta belgidan iborat bo‘lishi kerak. Masalan: +998901234567', regex='^\\+998\\d{9}$')]),
        ),
    ]
