# Generated by Django 5.2.6 on 2025-09-09 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configapp', '0006_user_name_user_surname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
